<a href="https://colab.research.google.com/github/dandaocta1/Data-Cleansing-Karyawan/blob/main/2418008_DataCleansing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DATA CLEANSING**

**import library Dan Menghubungkan Ke Google  Drive**

In [1]:
import pandas as pd
import numpy as np

# Membaca dataset dari file yang baru saja kamu upload
file_name = 'Analisis Kinerja dan Penggajian Karyawan Perusahaan.xlsx'
df = pd.read_excel(file_name, header=1)

print("=== DATASET AWAL (40 Baris) ===")
df.head(10)

=== DATASET AWAL (40 Baris) ===

   No. ID KARYAWAN             NAMA DEPARTEMEN USIA        GAJI RANTING KERJA
0    1        E001     Budi Santoso         IT   28   100000000         Baik
1    2        E002  Revanka Antonio        HRD   25     2000000    Cukup Baik
2    3        E003     Rehan Andika         it   21         Nan        Kurang
3    4        E004     Rizki Candra    Finance  222    12000000         Baik
4    5        E005    Hun Mie Sheng        Hrd   -3    12000000  Sangat Buruk
5    6        E006         Xiao Yan  Pemasaran   32         ss-         Cukup
6    7        E007          Yao Lao  Marketing   34  5000000000        Kurang
7    8        E007     Melina Putri         IT   36      500000            c-
8    9        E007    Indira Seruni        hrD   21      300000         Baik
9   10        E010     Tono Hartono         HR   50     4000000         Baik

# **Membaca** **DataSet** **Karyawan**

In [2]:
import pandas as pd

# Nama file Excel yang sudah di-upload ke Colab
file_name = 'Analisis Kinerja dan Penggajian Karyawan Perusahaan.xlsx'

# Membaca data Excel (menggunakan header=1 karena nama kolom ada di baris ke-2)
df = pd.read_excel(file_name, header=1)

# Menampilkan 10 data pertama
display(df.head(10))

# Menampilkan informasi jumlah data dan tipe data per kolom
print("\n=== INFORMASI DATASET ===")
df.info()

   No. ID KARYAWAN             NAMA DEPARTEMEN USIA        GAJI RANTING KERJA
0    1        E001     Budi Santoso         IT   28   100000000         Baik
1    2        E002  Revanka Antonio        HRD   25     2000000    Cukup Baik
2    3        E003     Rehan Andika         it   21         Nan        Kurang
3    4        E004     Rizki Candra    Finance  222    12000000         Baik
4    5        E005    Hun Mie Sheng        Hrd   -3    12000000  Sangat Buruk
5    6        E006         Xiao Yan  Pemasaran   32         ss-         Cukup
6    7        E007          Yao Lao  Marketing   34  5000000000        Kurang
7    8        E007     Melina Putri         IT   36      500000            c-
8    9        E007    Indira Seruni        hrD   21      300000         Baik
9   10        E010     Tono Hartono         HR   50     4000000         Baik

=== INFORMASI DATASET ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   No.            40 non-null     int64
 1   ID KARYAWAN    40 non-null     object
 2    NAMA          40 non-null     object
 3   DEPARTEMEN     40 non-null     object
 4   USIA           40 non-null     object
 5   GAJI           40 non-null     object
 6   RANTING KERJA  40 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.3+ KB

# **Menampikan** **Struktur** **Variabel** **Data** **Karyawan**

In [3]:
import pandas as pd

# 1. Membaca dataset (header=1 karena nama kolom ada di baris ke-2)
file_name = 'Analisis Kinerja dan Penggajian Karyawan Perusahaan.xlsx'
df = pd.read_excel(file_name, header=1)

# 2. Menampilkan Dimensi Data (Jumlah Baris & Kolom)
print(f"=== DIMENSI DATASET ===")
print(f"Jumlah Baris : {df.shape[0]}")
print(f"Jumlah Kolom : {df.shape[1]}\n")

# 3. Menampilkan Ringkasan Tipe Data dan Missing Value dasar
print("=== INFORMASI TIPE DATA & MISSING VALUE (df.info()) ===")
df.info()

# 4. Membuat Tabel Ringkasan Struktur Variabel yang Lebih Rapi
struktur_df = pd.DataFrame({
    'Nama Kolom': df.columns,
    'Tipe Data': df.dtypes.values,
    'Jumlah Non-Null': df.notnull().sum().values,
    'Jumlah Missing': df.isnull().sum().values,
    'Jumlah Nilai Unik': df.nunique().values,
    'Contoh Nilai': [df[col].dropna().iloc[0] if not df[col].dropna().empty else None for col in df.columns]
})

print("\n=== RINGKASAN STRUKTUR VARIABEL ===")
display(struktur_df)

=== DIMENSI DATASET ===
Jumlah Baris : 40
Jumlah Kolom : 7

=== INFORMASI TIPE DATA & MISSING VALUE (df.info()) ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   No.            40 non-null     int64
 1   ID KARYAWAN    40 non-null     object
 2    NAMA          40 non-null     object
 3   DEPARTEMEN     40 non-null     object
 4   USIA           40 non-null     object
 5   GAJI           40 non-null     object
 6   RANTING KERJA  40 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.3+ KB

=== RINGKASAN STRUKTUR VARIABEL ===

,Nama Kolom,Tipe Data,Jumlah Non-Null,Jumlah Missing,Jumlah Nilai Unik,Contoh Nilai
0,No.,int64,40,0,40,1
1,ID KARYAWAN,object,40,0,36,E001
2,NAMA,object,40,0,40,Budi Santoso
3,DEPARTEMEN,object,40,0,22,IT
4,USIA,object,40,0,27,28
5,GAJI,object,40,0,35,100000000
6,RANTING KERJA,object,40,0,19,Baik

# **Data** **Cleansing** - **Pembersihan** **Header** **&** **Nama** **Kolom**

Mengeliminasi spasi tersembunyi pada nama kolom, menghapus kolom No. yang tidak terpakai, dan merapikan nama Rating Kerja menjadi Rating Kerja

In [4]:
# Merapikan spasi pada nama kolom
df.columns = df.columns.str.strip()

# Hapus kolom 'No.' jika ada
if 'No.' in df.columns:
    df = df.drop(columns=['No.'])

# Rename typo nama kolom RANTING KERJA -> RATING KERJA
df = df.rename(columns={'RANTING KERJA': 'RATING KERJA'})

print("Nama Kolom Setelah Dirapikan:")
print(df.columns.tolist())

Nama Kolom Setelah Dirapikan:
['ID KARYAWAN', 'NAMA', 'DEPARTEMEN', 'USIA', 'GAJI', 'RATING KERJA']

# **Data** **Cleansing** - **Standarisasi** **Kolom** **ID** **Karyawan**

Mengatasi ID ganda/duplikat dan format rusak seperti E00- dengan membentuk ID baru yang unik, rapi, dan konsisten dari E001 hingga E040

In [6]:
# Memperbaiki ID Karyawan agar Unik dan Konsisten (E001 - E040)
df['ID KARYAWAN'] = [f'E{i+1:03d}' for i in range(len(df))]

print("Hasil Standarisasi ID Karyawan (10 Data Pertama):")
display(df[['ID KARYAWAN', 'NAMA']].head(40))

Hasil Standarisasi ID Karyawan (10 Data Pertama):

   ID KARYAWAN               NAMA
0         E001       Budi Santoso
1         E002    Revanka Antonio
2         E003       Rehan Andika
3         E004       Rizki Candra
4         E005      Hun Mie Sheng
5         E006           Xiao Yan
6         E007            Yao Lao
7         E008       Melina Putri
8         E009      Indira Seruni
9         E010       Tono Hartono
10        E011      Hadi Sumilang
11        E012      Koharu Kimito
12        E013        Oreki Hanta
13        E014         Wilian Neo
14        E015        Ahmad Dhani
15        E016       Uzumaki Yudi
16        E017   Fushiguro Rahmat
17        E018        Itadori Eko
18        E019     Kageyama Tobio
19        E020       Hinata Shoyo
20        E021     Kindaichi Yuji
21        E022      Ruichi Kunimi
22        E023       Bejan Kerdil
23        E024       Daniel Putra
24        E025          Upin Yono
25        E026          Ipin Yini
26        E027        Putri Hyuna
27        E028       Oreki Hutaro
28        E029        Oikawa Nomi
29        E030  Cristiano Ronaldo
30        E031        Cole Klemer
31        E032       Lamine Yahma
32        E033        Marco Reuss
33        E034           Na heedo
34        E035         Doona Suzy
35        E036         Sayo Putri
36        E037       Chintada Eru
37        E038           Wang Lin
38        E039      Doni Setiawan
39        E040       Aldean Tegar

# **Data** **Cleansing** - **Standarisasi** **Kolom** **Nama**

Tahap ini dilakukan untuk merapikan format penulisan nama karyawan. Pembersihan meliputi penghapusan spasi liar di awal/akhir teks trimming serta pengubahan format huruf menjadi Title Case huruf kapital di setiap awal kata agar tampilan data rapi dan konsisten

In [8]:
# Pengaturan agar Colab menampilkan seluruh baris tanpa terpotong
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print("=== TOTAL DATASET BERSIH (40 BARIS KARYAWAN) ===")
display(df)

=== TOTAL DATASET BERSIH (40 BARIS KARYAWAN) ===

,ID KARYAWAN,NAMA,DEPARTEMEN,USIA,GAJI,RATING KERJA
0,E001,Budi Santoso,IT,28,100000000,Baik
1,E002,Revanka Antonio,HRD,25,2000000,Cukup Baik
2,E003,Rehan Andika,it,21,Nan,Kurang
3,E004,Rizki Candra,Finance,222,12000000,Baik
4,E005,Hun Mie Sheng,Hrd,-3,12000000,Sangat Buruk
5,E006,Xiao Yan,Pemasaran,32,ss-,Cukup
6,E007,Yao Lao,Marketing,34,5000000000,Kurang
7,E008,Melina Putri,IT,36,500000,c-
8,E009,Indira Seruni,hrD,21,300000,Baik
9,E010,Tono Hartono,HR,50,4000000,Baik
10,E011,Hadi Sumilang,Keuangan,?,4000000,Baik
11,E012,Koharu Kimito,Finance,99,4000000,Baik
12,E013,Oreki Hanta,Pemasaran,999,2000000,Cukup
13,E014,Wilian Neo,hrd,23,10000000,Cukup
14,E015,Ahmad Dhani,IT,43,130000,Cukup
15,E016,Uzumaki Yudi,IT,24,1000000,Sangat Baik
16,E017,Fushiguro Rahmat,it,53,40000000,Sangat Baik
17,E018,Itadori Eko,iT,19,6000000,Sangat Baik
18,E019,Kageyama Tobio,Marketing,20,7000000,Cukup
19,E020,Hinata Shoyo,marKetiNG,dua puluh,800000,Cikip
20,E021,Kindaichi Yuji,finanCe,41,90000000,Buaikk
21,E022,Ruichi Kunimi,Pemasaran,24,11000000,Baikk
22,E023,Bejan Kerdil,Pemasaran,25,1500000,Baikk
23,E024,Daniel Putra,pEmasaRan,17,350000,Kurang
24,E025,Upin Yono,Keuangan,21,ho,Kurang
25,E026,Ipin Yini,HDR,21,5000000,Kurang
26,E027,Putri Hyuna,HRD,dua lima,3000000,Kureng
27,E028,Oreki Hutaro,Kuangan,35,1200000000,Sangar baik
28,E029,Oikawa Nomi,hDR,32,420000,Sanagt Baik
29,E030,Cristiano Ronaldo,Marketing,27,500000,Baik
30,E031,Cole Klemer,Youtuber,27,35000000,Baik
31,E032,Lamine Yahma,MAERKETING,28,23000000,Baik
32,E033,Marco Reuss,Finance,29,430000000,baik
33,E034,Na Heedo,Pemasaran,29,8200000,Cukup
34,E035,Doona Suzy,FInanCe,2-,92000000,sangat baik
35,E036,Sayo Putri,Marketing,43,67000000,sangat Baik
36,E037,Chintada Eru,IT,35,64000000,Sangar Kurang
37,E038,Wang Lin,it,23,2300000,Cukup Biak
38,E039,Doni Setiawan,Marketing,23,500,Baik
39,E040,Aldean Tegar,HRD,78,1000,Baik

# **Data** **Cleansing** - **Standarisasi** **Kolom** **Departemen**

 Bagian ini mengatasi inkonsistensi data kategorikal pada kolom DEPARTEMEN. Pembersihan dilakukan dengan menyelaraskan variasi huruf case sensitivit, memetakan istilah/sinonim bahasa Finance & Keuangan rightarrow Finance, Marketing & Pemasaran $\rightarrow$ Marketing, serta mengoreksi typo HDR, Kuangan menjadi 4 departemen utama IT, HRD, Finance, Marketing.

In [9]:
def clean_dept(val):
    val_str = str(val).strip().upper()
    if val_str in ['IT']: return 'IT'
    elif val_str in ['HRD', 'HR', 'HDR']: return 'HRD'
    elif val_str in ['FINANCE', 'KEUANGAN', 'KUANGAN']: return 'Finance'
    elif val_str in ['MARKETING', 'PEMASARAN', 'MAERKETING']: return 'Marketing'
    else: return 'Lainnya'

df['DEPARTEMEN'] = df['DEPARTEMEN'].apply(clean_dept)
display(df[['ID KARYAWAN', 'NAMA', 'DEPARTEMEN']])

   ID KARYAWAN               NAMA DEPARTEMEN
0         E001       Budi Santoso         IT
1         E002    Revanka Antonio        HRD
2         E003       Rehan Andika         IT
3         E004       Rizki Candra    Finance
4         E005      Hun Mie Sheng        HRD
5         E006           Xiao Yan  Marketing
6         E007            Yao Lao  Marketing
7         E008       Melina Putri         IT
8         E009      Indira Seruni        HRD
9         E010       Tono Hartono        HRD
10        E011      Hadi Sumilang    Finance
11        E012      Koharu Kimito    Finance
12        E013        Oreki Hanta  Marketing
13        E014         Wilian Neo        HRD
14        E015        Ahmad Dhani         IT
15        E016       Uzumaki Yudi         IT
16        E017   Fushiguro Rahmat         IT
17        E018        Itadori Eko         IT
18        E019     Kageyama Tobio  Marketing
19        E020       Hinata Shoyo  Marketing
20        E021     Kindaichi Yuji    Finance
21        E022      Ruichi Kunimi  Marketing
22        E023       Bejan Kerdil  Marketing
23        E024       Daniel Putra  Marketing
24        E025          Upin Yono    Finance
25        E026          Ipin Yini        HRD
26        E027        Putri Hyuna        HRD
27        E028       Oreki Hutaro    Finance
28        E029        Oikawa Nomi        HRD
29        E030  Cristiano Ronaldo  Marketing
30        E031        Cole Klemer    Lainnya
31        E032       Lamine Yahma  Marketing
32        E033        Marco Reuss    Finance
33        E034           Na Heedo  Marketing
34        E035         Doona Suzy    Finance
35        E036         Sayo Putri  Marketing
36        E037       Chintada Eru         IT
37        E038           Wang Lin         IT
38        E039      Doni Setiawan  Marketing
39        E040       Aldean Tegar        HRD

# **Data** **Cleansing** - **Standarisasi** **Kolom** **Usia**

engonversi teks angka ke numerik 'dua puluh' 20, membuang karakter pengotor '?', '2-', menyaring nilai outlier di luar batas usia produktif wajar 18–65 tahun, dan mengimputasi nilai kosong dengan nilai Median usia

In [10]:
def clean_usia(val):
    val_str = str(val).strip().lower()
    if val_str in ['dua puluh', '20']:
        return 20.0
    elif val_str in ['dua lima', '25']:
        return 25.0
    elif val_str in ['?', '2-', 'nan', 'none']:
        return np.nan

    try:
        num = float(val_str)
        if num < 18 or num > 65:
            return np.nan
        return num
    except:
        return np.nan

df['USIA'] = df['USIA'].apply(clean_usia)

# Imputasi dengan Median Usia
median_usia = df['USIA'].median()
df['USIA'] = df['USIA'].fillna(median_usia).astype(int)

print("=== HASIL STANDARISASI USIA (40 BARIS) ===")
display(df[['ID KARYAWAN', 'NAMA', 'USIA']])

=== HASIL STANDARISASI USIA (40 BARIS) ===

   ID KARYAWAN               NAMA  USIA
0         E001       Budi Santoso    28
1         E002    Revanka Antonio    25
2         E003       Rehan Andika    21
3         E004       Rizki Candra    27
4         E005      Hun Mie Sheng    27
5         E006           Xiao Yan    32
6         E007            Yao Lao    34
7         E008       Melina Putri    36
8         E009      Indira Seruni    21
9         E010       Tono Hartono    50
10        E011      Hadi Sumilang    27
11        E012      Koharu Kimito    27
12        E013        Oreki Hanta    27
13        E014         Wilian Neo    23
14        E015        Ahmad Dhani    43
15        E016       Uzumaki Yudi    24
16        E017   Fushiguro Rahmat    53
17        E018        Itadori Eko    19
18        E019     Kageyama Tobio    20
19        E020       Hinata Shoyo    20
20        E021     Kindaichi Yuji    41
21        E022      Ruichi Kunimi    24
22        E023       Bejan Kerdil    25
23        E024       Daniel Putra    27
24        E025          Upin Yono    21
25        E026          Ipin Yini    21
26        E027        Putri Hyuna    25
27        E028       Oreki Hutaro    35
28        E029        Oikawa Nomi    32
29        E030  Cristiano Ronaldo    27
30        E031        Cole Klemer    27
31        E032       Lamine Yahma    28
32        E033        Marco Reuss    29
33        E034           Na Heedo    29
34        E035         Doona Suzy    27
35        E036         Sayo Putri    43
36        E037       Chintada Eru    35
37        E038           Wang Lin    23
38        E039      Doni Setiawan    23
39        E040       Aldean Tegar    27

# **Data** **Cleansing** - **Standarisasi** **Kolom** **Gaji**

Membersihkan karakter non-numerik 'ss-', 'ho' dan mengatasi outlier ekstrem. Nilai gaji di luar rentang wajar diimputasi menggunakan Median Gaji berdasarkan Departemen masing-masing.

In [13]:
# 1. Fungsi penyaringan gaji (Rentang Rp 1.000.000 s/d Rp 40.000.000)
def clean_gaji_40m(val):
  val_str = str(val).strip().lower()
  try:
    num = float(val_str)
    # Saring nilai di luar 1 Juta s/d 40 Juta menjadi NaN
    if num < 1000000 or num > 40000000:
      return np.nan
    return num
  except:
    # Mengubah string/huruf/simbol (ss-, ho, Nan) menjadi NaN
    return np.nan


# 2. Terapkan pembersihan awal ke kolom GAJI
df['GAJI'] = df['GAJI'].apply(clean_gaji_40m)

# 3. Imputasi nilai NaN dengan Median Gaji per Departemen
group_medians = df.groupby('DEPARTEMEN')['GAJI'].transform('median')
df['GAJI'] = df['GAJI'].fillna(group_medians)

# 4. Jika masih ada NaN, isi dengan Median Keseluruhan
overall_median = df['GAJI'].median()
df['GAJI'] = df['GAJI'].fillna(overall_median)

# Tampilkan seluruh 40 data kolom GAJI yang sudah bersih
print("=== HASIL CLEANSING GAJI (BATAS MAKSIMAL 40 JUTA) ===")
display(df[['ID KARYAWAN', 'NAMA', 'DEPARTEMEN', 'GAJI']])

=== HASIL CLEANSING GAJI (BATAS MAKSIMAL 40 JUTA) ===

   ID KARYAWAN               NAMA DEPARTEMEN        GAJI
0         E001       Budi Santoso         IT  23000000.0
1         E002    Revanka Antonio        HRD   2000000.0
2         E003       Rehan Andika         IT  23000000.0
3         E004       Rizki Candra    Finance  12000000.0
4         E005      Hun Mie Sheng        HRD  12000000.0
5         E006           Xiao Yan  Marketing   8200000.0
6         E007            Yao Lao  Marketing   8200000.0
7         E008       Melina Putri         IT  23000000.0
8         E009      Indira Seruni        HRD   4500000.0
9         E010       Tono Hartono        HRD   4000000.0
10        E011      Hadi Sumilang    Finance   4000000.0
11        E012      Koharu Kimito    Finance   4000000.0
12        E013        Oreki Hanta  Marketing   2000000.0
13        E014         Wilian Neo        HRD  10000000.0
14        E015        Ahmad Dhani         IT  23000000.0
15        E016       Uzumaki Yudi         IT   1000000.0
16        E017   Fushiguro Rahmat         IT  40000000.0
17        E018        Itadori Eko         IT   6000000.0
18        E019     Kageyama Tobio  Marketing   7000000.0
19        E020       Hinata Shoyo  Marketing   8200000.0
20        E021     Kindaichi Yuji    Finance  12000000.0
21        E022      Ruichi Kunimi  Marketing  11000000.0
22        E023       Bejan Kerdil  Marketing   1500000.0
23        E024       Daniel Putra  Marketing   8200000.0
24        E025          Upin Yono    Finance  12000000.0
25        E026          Ipin Yini        HRD   5000000.0
26        E027        Putri Hyuna        HRD   3000000.0
27        E028       Oreki Hutaro    Finance  12000000.0
28        E029        Oikawa Nomi        HRD   4500000.0
29        E030  Cristiano Ronaldo  Marketing   8200000.0
30        E031        Cole Klemer    Lainnya  35000000.0
31        E032       Lamine Yahma  Marketing  23000000.0
32        E033        Marco Reuss    Finance  12000000.0
33        E034           Na Heedo  Marketing   8200000.0
34        E035         Doona Suzy    Finance  12000000.0
35        E036         Sayo Putri  Marketing   8200000.0
36        E037       Chintada Eru         IT  23000000.0
37        E038           Wang Lin         IT   2300000.0
38        E039      Doni Setiawan  Marketing   8200000.0
39        E040       Aldean Tegar        HRD   4500000.0

# **Data** **Cleansing** - **Standarisasi** **Kolom** **Rating** **Kerja**

Memetakan ulang seluruh variasi typo penulisan rating kerja ke dalam 6 skala standar Sangat Baik, Baik, Cukup Baik, Cukup, Kurang, Sangat Buruk dan mengisi nilai yang hilang dengan nilai Modus kategori terbanyak.

In [14]:
def clean_rating(val):
    val_str = str(val).strip().lower()
    if 'sangat baik' in val_str or 'sangar baik' in val_str or 'sanagt baik' in val_str:
        return 'Sangat Baik'
    elif 'cukup baik' in val_str or 'cukup biak' in val_str:
        return 'Cukup Baik'
    elif 'baik' in val_str or 'baikk' in val_str or 'buaikk' in val_str:
        return 'Baik'
    elif 'cukup' in val_str or 'cikip' in val_str:
        return 'Cukup'
    elif 'sangat buruk' in val_str:
        return 'Sangat Buruk'
    elif 'kurang' in val_str or 'kureng' in val_str or 'sangar kurang' in val_str:
        return 'Kurang'
    else:
        return np.nan

df['RATING KERJA'] = df['RATING KERJA'].apply(clean_rating)
df['RATING KERJA'] = df['RATING KERJA'].fillna(df['RATING KERJA'].mode()[0])

print("=== HASIL STANDARISASI RATING KERJA (40 BARIS) ===")
display(df[['ID KARYAWAN', 'NAMA', 'RATING KERJA']])

=== HASIL STANDARISASI RATING KERJA (40 BARIS) ===

   ID KARYAWAN               NAMA  RATING KERJA
0         E001       Budi Santoso          Baik
1         E002    Revanka Antonio    Cukup Baik
2         E003       Rehan Andika        Kurang
3         E004       Rizki Candra          Baik
4         E005      Hun Mie Sheng  Sangat Buruk
5         E006           Xiao Yan         Cukup
6         E007            Yao Lao        Kurang
7         E008       Melina Putri          Baik
8         E009      Indira Seruni          Baik
9         E010       Tono Hartono          Baik
10        E011      Hadi Sumilang          Baik
11        E012      Koharu Kimito          Baik
12        E013        Oreki Hanta         Cukup
13        E014         Wilian Neo         Cukup
14        E015        Ahmad Dhani         Cukup
15        E016       Uzumaki Yudi   Sangat Baik
16        E017   Fushiguro Rahmat   Sangat Baik
17        E018        Itadori Eko   Sangat Baik
18        E019     Kageyama Tobio         Cukup
19        E020       Hinata Shoyo         Cukup
20        E021     Kindaichi Yuji          Baik
21        E022      Ruichi Kunimi          Baik
22        E023       Bejan Kerdil          Baik
23        E024       Daniel Putra        Kurang
24        E025          Upin Yono        Kurang
25        E026          Ipin Yini        Kurang
26        E027        Putri Hyuna        Kurang
27        E028       Oreki Hutaro   Sangat Baik
28        E029        Oikawa Nomi   Sangat Baik
29        E030  Cristiano Ronaldo          Baik
30        E031        Cole Klemer          Baik
31        E032       Lamine Yahma          Baik
32        E033        Marco Reuss          Baik
33        E034           Na Heedo         Cukup
34        E035         Doona Suzy   Sangat Baik
35        E036         Sayo Putri   Sangat Baik
36        E037       Chintada Eru        Kurang
37        E038           Wang Lin    Cukup Baik
38        E039      Doni Setiawan          Baik
39        E040       Aldean Tegar          Baik

# **Data** **Cleansing** - **Deduplikasi** **&** **Pengecekan** **Missing** **Value**

Mengecek serta menghapus baris duplikat jika ada, lalu memverifikasi bahwa seluruh kolom sudah bebas dari nilai kosong missing value/NaN.

In [15]:
# Hapus baris duplikat
df = df.drop_duplicates()

# Pengecekan akhir nilai missing
print("=== PENGECEKAN NILAI MISSING PER KOLOM ===")
print(df.isnull().sum())

=== PENGECEKAN NILAI MISSING PER KOLOM ===
ID KARYAWAN     0
NAMA            0
DEPARTEMEN      0
USIA            0
GAJI            0
RATING KERJA    0
dtype: int64

# **Data** **Enrichment** **&** **Export** **Dataset** **Akhir**

Pada tahap ini dilakukan penambahan variabel/fitur turunan feature engineering yang relevan dengan domain analisis kinerja dan penggajian karyawan. Penambahan ini bertujuan untuk memperkaya informasi dataset tanpa mengubah, mengelompokkan, atau merusak variabel asli Usia dan Gaji.

In [18]:
# 1. Konversi Rating Kerja ke Skor Numerik (0 - 5)
rating_map = {
    'Sangat Baik': 5,
    'Baik': 4,
    'Cukup Baik': 3,
    'Cukup': 2,
    'Kurang': 1,
    'Sangat Buruk': 0,
}
df['SKOR_RATING'] = df['RATING KERJA'].map(rating_map)

# 2. Perhitungan Akumulasi Gaji Tahunan (12 Bulan)
df['GAJI_TAHUNAN'] = df['GAJI'] * 12

# 3. Selisih Gaji Karyawan Dibanding Rata-rata Departemennya
df['RATA_GAJI_DEPT'] = df.groupby('DEPARTEMEN')['GAJI'].transform('mean')
df['SELISIH_GAJI_DEPT'] = (df['GAJI'] - df['RATA_GAJI_DEPT']).round(0)

# Hapus kolom bantu rata-rata agar dataset tetap rapi
df = df.drop(columns=['RATA_GAJI_DEPT'])

# Pengaturan Tampilan Pandas (Menampilkan Seluruh 40 Baris)
pd.set_option('display.max_rows', 50)

print("=== HASIL AKHIR DATASET KARYAWAN SETELAH DATA ENRICHMENT (40 BARIS) ===")
display(df)

# Simpan Ke File Excel Bersih
df.to_excel('Data_Karyawan_Cleaned.xlsx', index=False)
print("\n✅ File dataset bersih berhasil disimpan: 'Data_Karyawan_Cleaned.xlsx'")

=== HASIL AKHIR DATASET KARYAWAN SETELAH DATA ENRICHMENT (40 BARIS) ===

,ID KARYAWAN,NAMA,DEPARTEMEN,USIA,GAJI,RATING KERJA,KELOMPOK_USIA,KATEGORI_GAJI,SKOR_RATING,GAJI_TAHUNAN,SELISIH_GAJI_DEPT
0,E001,Budi Santoso,IT,28,23000000.0,Baik,Produktif (25-35),Tinggi,4,276000000.0,4744444.0
1,E002,Revanka Antonio,HRD,25,2000000.0,Cukup Baik,Muda (<25),Rendah,3,24000000.0,-3500000.0
2,E003,Rehan Andika,IT,21,23000000.0,Kurang,Muda (<25),Tinggi,1,276000000.0,4744444.0
3,E004,Rizki Candra,Finance,27,12000000.0,Baik,Produktif (25-35),Sedang,4,144000000.0,2000000.0
4,E005,Hun Mie Sheng,HRD,27,12000000.0,Sangat Buruk,Produktif (25-35),Sedang,0,144000000.0,6500000.0
5,E006,Xiao Yan,Marketing,32,8200000.0,Cukup,Produktif (25-35),Sedang,2,98400000.0,-269231.0
6,E007,Yao Lao,Marketing,34,8200000.0,Kurang,Produktif (25-35),Sedang,1,98400000.0,-269231.0
7,E008,Melina Putri,IT,36,23000000.0,Baik,Senior (>35),Tinggi,4,276000000.0,4744444.0
8,E009,Indira Seruni,HRD,21,4500000.0,Baik,Muda (<25),Rendah,4,54000000.0,-1000000.0
9,E010,Tono Hartono,HRD,50,4000000.0,Baik,Senior (>35),Rendah,4,48000000.0,-1500000.0
10,E011,Hadi Sumilang,Finance,27,4000000.0,Baik,Produktif (25-35),Rendah,4,48000000.0,-6000000.0
11,E012,Koharu Kimito,Finance,27,4000000.0,Baik,Produktif (25-35),Rendah,4,48000000.0,-6000000.0
12,E013,Oreki Hanta,Marketing,27,2000000.0,Cukup,Produktif (25-35),Rendah,2,24000000.0,-6469231.0
13,E014,Wilian Neo,HRD,23,10000000.0,Cukup,Muda (<25),Sedang,2,120000000.0,4500000.0
14,E015,Ahmad Dhani,IT,43,23000000.0,Cukup,Senior (>35),Tinggi,2,276000000.0,4744444.0
15,E016,Uzumaki Yudi,IT,24,1000000.0,Sangat Baik,Muda (<25),Rendah,5,12000000.0,-17255556.0
16,E017,Fushiguro Rahmat,IT,53,40000000.0,Sangat Baik,Senior (>35),Tinggi,5,480000000.0,21744444.0
17,E018,Itadori Eko,IT,19,6000000.0,Sangat Baik,Muda (<25),Sedang,5,72000000.0,-12255556.0
18,E019,Kageyama Tobio,Marketing,20,7000000.0,Cukup,Muda (<25),Sedang,2,84000000.0,-1469231.0
19,E020,Hinata Shoyo,Marketing,20,8200000.0,Cukup,Muda (<25),Sedang,2,98400000.0,-269231.0
20,E021,Kindaichi Yuji,Finance,41,12000000.0,Baik,Senior (>35),Sedang,4,144000000.0,2000000.0
21,E022,Ruichi Kunimi,Marketing,24,11000000.0,Baik,Muda (<25),Sedang,4,132000000.0,2530769.0
22,E023,Bejan Kerdil,Marketing,25,1500000.0,Baik,Muda (<25),Rendah,4,18000000.0,-6969231.0
23,E024,Daniel Putra,Marketing,27,8200000.0,Kurang,Produktif (25-35),Sedang,1,98400000.0,-269231.0
24,E025,Upin Yono,Finance,21,12000000.0,Kurang,Muda (<25),Sedang,1,144000000.0,2000000.0
25,E026,Ipin Yini,HRD,21,5000000.0,Kurang,Muda (<25),Rendah,1,60000000.0,-500000.0
26,E027,Putri Hyuna,HRD,25,3000000.0,Kurang,Muda (<25),Rendah,1,36000000.0,-2500000.0
27,E028,Oreki Hutaro,Finance,35,12000000.0,Sangat Baik,Produktif (25-35),Sedang,5,144000000.0,2000000.0
28,E029,Oikawa Nomi,HRD,32,4500000.0,Sangat Baik,Produktif (25-35),Rendah,5,54000000.0,-1000000.0
29,E030,Cristiano Ronaldo,Marketing,27,8200000.0,Baik,Produktif (25-35),Sedang,4,98400000.0,-269231.0
30,E031,Cole Klemer,Lainnya,27,35000000.0,Baik,Produktif (25-35),Tinggi,4,420000000.0,0.0
31,E032,Lamine Yahma,Marketing,28,23000000.0,Baik,Produktif (25-35),Tinggi,4,276000000.0,14530769.0
32,E033,Marco Reuss,Finance,29,12000000.0,Baik,Produktif (25-35),Sedang,4,144000000.0,2000000.0
33,E034,Na Heedo,Marketing,29,8200000.0,Cukup,Produktif (25-35),Sedang,2,98400000.0,-269231.0
34,E035,Doona Suzy,Finance,27,12000000.0,Sangat Baik,Produktif (25-35),Sedang,5,144000000.0,2000000.0
35,E036,Sayo Putri,Marketing,43,8200000.0,Sangat Baik,Senior (>35),Sedang,5,98400000.0,-269231.0
36,E037,Chintada Eru,IT,35,23000000.0,Kurang,Produktif (25-35),Tinggi,1,276000000.0,4744444.0
37,E038,Wang Lin,IT,23,2300000.0,Cukup Baik,Muda (<25),Rendah,3,27600000.0,-15955556.0
38,E039,Doni Setiawan,Marketing,23,8200000.0,Baik,Muda (<25),Sedang,4,98400000.0,-269231.0
39,E040,Aldean Tegar,HRD,27,4500000.0,Baik,Produktif (25-35),Rendah,4,54000000.0,-1000000.0

✅ File dataset bersih berhasil disimpan: 'Data_Karyawan_Cleaned.xlsx'